import { Request, Response } from 'express';

// 14 destinations dataset for server API
const DESTINATIONS = [
  {
    id: 'mahabalipuram',
    name: 'Mahabalipuram',
    tamilName: 'மகாபலிபுரம்',
    tagline: 'Where history meets the sea.',
    description: 'An ancient coastal seaport of the Pallava dynasty, renowned for rock-cut monoliths and UNESCO World Heritage shore temples.',
    location: 'Chengalpattu District',
    district: 'Chengalpattu',
    category: 'Heritage',
    rating: 4.8,
    reviewCount: 3840,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [12.6269, 80.1927],
    bestTime: 'October to March',
    entryFee: 40,
    duration: '3–4 hours',
    estimatedCost: 800,
    crowdLevel: 'HIGH',
    highlights: ['UNESCO Shore Temple', "Arjuna's Penance", "Krishna's Butterball", 'Five Rathas'],
    history: 'Built under Narasimhavarman I in the 7th century CE as a major naval trading gateway to Southeast Asia.',
    architecture: 'Pioneered monolithic Dravidian rock-cut and structural granite architecture.',
    culturalSignificance: 'UNESCO World Heritage monument grouping.',
    audioGuideText: 'Welcome to Mahabalipuram. As you stand before the Shore Temple, listen to the Bay of Bengal waves crashing against 1,300-year-old carved granite.'
  },
  {
    id: 'chennai',
    name: 'Chennai',
    tamilName: 'சென்னை',
    tagline: 'The Gateway to South India & Cultural Capital.',
    description: 'Vibrant metropolitan cradle of Carnatic music, ancient Dravidian temples, and Marina beach.',
    location: 'Chennai District',
    district: 'Chennai',
    category: 'Culture',
    rating: 4.7,
    reviewCount: 9120,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [13.0827, 80.2707],
    bestTime: 'November to February',
    entryFee: 0,
    duration: '1–2 days',
    estimatedCost: 1500,
    crowdLevel: 'MEDIUM',
    highlights: ['Kapaleeshwarar Temple', 'Marina Beach', 'San Thome Basilica'],
    history: 'Ancient Chola port villages like Mylapore evolved into the capital of Tamil Nadu.',
    architecture: 'Dravidian gopurams juxtaposed with Indo-Saracenic colonial structures.',
    culturalSignificance: 'Capital of Tamil culture and Carnatic music.',
    audioGuideText: 'Welcome to Chennai, where ancient traditions blend with urban energy.'
  },
  {
    id: 'kanchipuram',
    name: 'Kanchipuram',
    tamilName: 'காஞ்சிபுரம்',
    tagline: 'The Golden City of a Thousand Temples & Silk.',
    description: 'One of India\'s seven sacred Moksha puris, celebrated for monumental temple spires and master silk weavers.',
    location: 'Kanchipuram District',
    district: 'Kanchipuram',
    category: 'Temples',
    rating: 4.8,
    reviewCount: 4210,
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    coordinates: [12.8342, 79.7036],
    bestTime: 'October to March',
    entryFee: 0,
    duration: '4–6 hours',
    estimatedCost: 1200,
    crowdLevel: 'MEDIUM',
    highlights: ['Ekambareswarar Temple', 'Kanchi Kailasanathar Temple', 'Silk Weaving Looms'],
    history: 'Historical capital of the Pallavas from the 4th to 9th centuries CE.',
    architecture: 'Oldest sandstone temples in South India.',
    culturalSignificance: 'UNESCO GI Tagged pure mulberry silk with gold zari.',
    audioGuideText: 'Entering Kanchipuram, hear the rhythmic clatter of pit looms weaving pure mulberry silk.'
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    tamilName: 'பாண்டிச்சேரி',
    tagline: 'A French Colonial Coastal Promenade.',
    description: 'A serene union of French colonial elegance, pastel villas, tree-lined boulevards, and tranquil ashrams.',
    location: 'Puducherry UT',
    district: 'Puducherry',
    category: 'Beaches',
    rating: 4.8,
    reviewCount: 6890,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [11.9416, 79.8083],
    bestTime: 'October to March',
    entryFee: 0,
    duration: '1–2 days',
    estimatedCost: 2000,
    crowdLevel: 'MEDIUM',
    highlights: ['Promenade Beach', 'Auroville Matrimandir', 'French Quarter'],
    history: 'French colonial enclave from 1674 to 1954.',
    architecture: 'Neoclassical Franco-Tamil villas with mustard arches.',
    culturalSignificance: 'Universal human unity at Auroville and Sri Aurobindo Ashram.',
    audioGuideText: 'Breathe in the sea air and fresh croissants in White Town.'
  },
  {
    id: 'thanjavur',
    name: 'Thanjavur',
    tamilName: 'தஞ்சாவூர்',
    tagline: 'The Imperial Throne of the Great Cholas.',
    description: 'Home of the breathtaking Brihadeeswara Temple, Maratha Palace, and Tanjore art.',
    location: 'Thanjavur District',
    district: 'Thanjavur',
    category: 'Heritage',
    rating: 4.9,
    reviewCount: 5420,
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=1200&q=80',
    coordinates: [10.7870, 79.1378],
    bestTime: 'October to March',
    entryFee: 0,
    duration: '4–5 hours',
    estimatedCost: 950,
    crowdLevel: 'MEDIUM',
    highlights: ['Brihadeeswarar Big Temple', 'Maratha Palace', 'Saraswathi Mahal Library'],
    history: 'Built by Emperor Raja Raja Chola I between 1003 and 1010 CE.',
    architecture: '66-meter high granite vimana with 80-ton monolithic cupola.',
    culturalSignificance: 'UNESCO Great Living Chola Temples. Birthplace of Bharatanatyam.',
    audioGuideText: 'Behold the Big Temple, an architectural miracle of 130,000 tons of granite.'
  },
  {
    id: 'madurai',
    name: 'Madurai',
    tamilName: 'மதுரை',
    tagline: 'The Sleepless City of Jasmine and Pandyan Kings.',
    description: 'Ancient city centered around the magnificent Meenakshi Amman Temple and night food stalls.',
    location: 'Madurai District',
    district: 'Madurai',
    category: 'Culture',
    rating: 4.9,
    reviewCount: 8870,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [9.9252, 78.1198],
    bestTime: 'October to March',
    entryFee: 50,
    duration: '1–2 days',
    estimatedCost: 1400,
    crowdLevel: 'HIGH',
    highlights: ['Meenakshi Amman Temple', 'Thirumalai Nayakkar Mahal', 'Jigarthanda'],
    history: 'Legendary capital of the Tamil Sangam poets and Pandyan dynasty.',
    architecture: '14 towering gopurams adorned with 33,000 sculpted figures.',
    culturalSignificance: 'The heartland of classical Tamil literature.',
    audioGuideText: 'Vanakkam to Madurai! Walk through concentric lotus streets as evening bells echo.'
  },
  {
    id: 'trichy',
    name: 'Trichy (Tiruchirappalli)',
    tamilName: 'திருச்சிராப்பள்ளி',
    tagline: 'Ancient Rock Fortress on the banks of Kaveri.',
    description: 'Dominated by the 83-meter Rockfort and Srirangam temple complex.',
    location: 'Tiruchirappalli District',
    district: 'Tiruchirappalli',
    category: 'Temples',
    rating: 4.7,
    reviewCount: 4620,
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    coordinates: [10.7905, 78.7047],
    bestTime: 'November to February',
    entryFee: 20,
    duration: '1 day',
    estimatedCost: 1100,
    crowdLevel: 'MEDIUM',
    highlights: ['Rockfort Temple', 'Srirangam Ranganathaswamy', 'Kallanai Dam'],
    history: 'Geological formation dating back over a billion years.',
    architecture: 'Srirangam spans 156 acres with 21 gopurams.',
    culturalSignificance: 'Prime center of Sri Vaishnavism.',
    audioGuideText: 'Ascend the rock tunnel for a panoramic vista of the sacred Kaveri river.'
  },
  {
    id: 'rameswaram',
    name: 'Rameswaram',
    tamilName: 'இராமேஸ்வரம்',
    tagline: 'The Sacred Island & Coastal Gateway to the Coral Seas.',
    description: 'Enchanting island reached via the historic Pamban Bridge with endless temple corridors and Dhanushkodi ghost town.',
    location: 'Ramanathapuram District',
    district: 'Ramanathapuram',
    category: 'Heritage',
    rating: 4.8,
    reviewCount: 6100,
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    coordinates: [9.2876, 79.3129],
    bestTime: 'October to April',
    entryFee: 0,
    duration: '1–2 days',
    estimatedCost: 1600,
    crowdLevel: 'HIGH',
    highlights: ['Pamban Sea Bridge', 'Ramanathaswamy Temple Corridors', 'Dhanushkodi'],
    history: 'Legendary bridge site connecting India and Sri Lanka.',
    architecture: 'Longest temple corridor in the world (1,220 meters).',
    culturalSignificance: 'One of the Char Dham pilgrimage sacred sites.',
    audioGuideText: 'Cross the azure ocean over Pamban Bridge to reach this sacred island.'
  },
  {
    id: 'kanyakumari',
    name: 'Kanyakumari',
    tamilName: 'கன்னியாகுமரி',
    tagline: 'Where Three Oceans Meet at the Tip of India.',
    description: 'Southernmost point of India where Arabian Sea, Indian Ocean, and Bay of Bengal converge.',
    location: 'Kanyakumari District',
    district: 'Kanyakumari',
    category: 'Beaches',
    rating: 4.8,
    reviewCount: 7120,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [8.0883, 77.5385],
    bestTime: 'October to March',
    entryFee: 70,
    duration: '1 day',
    estimatedCost: 1300,
    crowdLevel: 'HIGH',
    highlights: ['Vivekananda Rock', '133-ft Thiruvalluvar Statue', 'Triveni Sangam'],
    history: 'Ancient southern boundary of Tamilakam celebrated in Sangam poetry.',
    architecture: '133-ft stone Thiruvalluvar sculpture weighing 7,000 tonnes.',
    culturalSignificance: 'Tri-sea confluence and Swami Vivekananda meditation site.',
    audioGuideText: 'Stand at the tip of the subcontinent and watch the sunrise over three converging seas.'
  },
  {
    id: 'ooty',
    name: 'Ooty (Udhagamandalam)',
    tamilName: 'ஊட்டி',
    tagline: 'The Queen of Hill Stations in the Blue Mountains.',
    description: 'Misty Nilgiri Hills with eucalyptus groves, tea gardens, and UNESCO toy train.',
    location: 'Nilgiris District',
    district: 'Nilgiris',
    category: 'Hill Station',
    rating: 4.8,
    reviewCount: 8200,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [11.4102, 76.6950],
    bestTime: 'October to June',
    entryFee: 50,
    duration: '2–3 days',
    estimatedCost: 2800,
    crowdLevel: 'HIGH',
    highlights: ['Nilgiri Mountain Railway', 'Botanical Gardens', 'Doddabetta Peak'],
    history: 'Developed in the 1820s as summer capital of Madras Presidency.',
    architecture: 'Colonial stone cottages and Toda tribal dwellings.',
    culturalSignificance: 'Heritage of indigenous Nilgiri communities.',
    audioGuideText: 'Hear the whistle of the blue steam train as you travel through fragrant eucalyptus hills.'
  },
  {
    id: 'kodaikanal',
    name: 'Kodaikanal',
    tamilName: 'கொடைக்கானல்',
    tagline: 'The Princess of Hill Stations & Misty Lakes.',
    description: 'Sanctuary atop the Palani Hills with star-shaped lake and pine forests.',
    location: 'Dindigul District',
    district: 'Dindigul',
    category: 'Hill Station',
    rating: 4.8,
    reviewCount: 6490,
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    coordinates: [10.2381, 77.4892],
    bestTime: 'September to May',
    entryFee: 30,
    duration: '2–3 days',
    estimatedCost: 2600,
    crowdLevel: 'MEDIUM',
    highlights: ['Kodaikanal Lake', "Coaker's Walk", 'Pillar Rocks'],
    history: 'Established in 1845 as a mountain retreat.',
    architecture: 'Charming stone cottages and wooden boathouses.',
    culturalSignificance: 'Bloom site of the rare 12-year Kurinji flower.',
    audioGuideText: 'Stroll along Coaker\'s Walk as rolling clouds blanket the valleys below.'
  },
  {
    id: 'chettinad',
    name: 'Chettinad (Karaikudi)',
    tamilName: 'செட்டிநாடு',
    tagline: 'Palaces of Teak, Athangudi Tiles & Legendary Spice.',
    description: 'Heritage wonderland of mansions with Burmese teak, handmade tiles, and world-famous cuisine.',
    location: 'Sivaganga District',
    district: 'Sivaganga',
    category: 'Village Experiences',
    rating: 4.9,
    reviewCount: 3120,
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    coordinates: [10.0717, 78.7836],
    bestTime: 'October to March',
    entryFee: 100,
    duration: '1–2 days',
    estimatedCost: 2200,
    crowdLevel: 'LOW',
    highlights: ['Kanadukathan Palace', 'Athangudi Tiles', 'Banana Leaf Feast'],
    history: 'Built by the affluent Nattukottai Chettiars in the 19th century.',
    architecture: 'Palaces with hundreds of rooms, Italian marble, and Burmese teak.',
    culturalSignificance: 'World-renowned Chettinad culinary traditions.',
    audioGuideText: 'Step into a regal courtyard where solid teak columns welcome you into Chettiar warmth.'
  },
  {
    id: 'coimbatore',
    name: 'Coimbatore',
    tamilName: 'கோயம்புத்தூர்',
    tagline: 'The Manchester of South India at the Western Ghats.',
    description: 'Industrial and spiritual gateway home to the 112-ft Adiyogi Shiva and Siruvani sweet water.',
    location: 'Coimbatore District',
    district: 'Coimbatore',
    category: 'Nature',
    rating: 4.7,
    reviewCount: 5200,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    coordinates: [11.0168, 76.9558],
    bestTime: 'September to March',
    entryFee: 0,
    duration: '1–2 days',
    estimatedCost: 1500,
    crowdLevel: 'MEDIUM',
    highlights: ['Adiyogi Shiva', 'Marudhamalai Temple', 'Siruvani Falls'],
    history: 'Ancient Kongu Nadu trade corridor.',
    architecture: 'Colossal 112-ft steel Adiyogi sculpture.',
    culturalSignificance: 'Renowned for Siruvani water and textile heritage.',
    audioGuideText: 'Gaze upon the majestic silhouette of Adiyogi set against the misty Velliangiri foothills.'
  },
  {
    id: 'yercaud',
    name: 'Yercaud',
    tamilName: 'ஏற்காடு',
    tagline: 'The Jewel of the Shevaroy Hills.',
    description: 'Tranquil hill retreat surrounded by coffee plantations, orange groves, and Emerald Lake.',
    location: 'Salem District',
    district: 'Salem',
    category: 'Hill Station',
    rating: 4.6,
    reviewCount: 3100,
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    coordinates: [11.7753, 78.2093],
    bestTime: 'October to June',
    entryFee: 20,
    duration: '1–2 days',
    estimatedCost: 1800,
    crowdLevel: 'LOW',
    highlights: ['Yercaud Lake', "Lady's Seat", 'Coffee Plantations'],
    history: 'Discovered in the 1820s by Scottish administrator David Cockburn.',
    architecture: 'Stone chapels and colonial coffee bungalows.',
    culturalSignificance: 'Highest peak in the Eastern Ghats of Tamil Nadu.',
    audioGuideText: 'Wind through twenty hairpin turns to find serene lake waters reflecting silver oaks.'
  }
];

export const getDestinations = async (_req: Request, res: Response) => {
  return res.json(DESTINATIONS);
};

export const getDestinationById = async (req: Request, res: Response) => {
  const dest = DESTINATIONS.find((d) => d.id === req.params.id);
  if (!dest) {
    return res.status(404).json({ message: 'Destination not found' });
  }
  return res.json(dest);
};
